config/routes.rb
Rails.application.routes.draw do
  get 'news/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'restaurants#index'
  resources :restaurants do
    resources :items
  end
  
  get "users/:id", to: "users#show", as: "user"
  get '/restaurant_orders', to: 'orders#restaurant_orders', as: 'restaurant_orders'


  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  resources :order_items
  resources :carts
  resources :orders

  
  resources :rooms do
    resources :messages
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  def add_item(item)
    existing_restaurant_id = order_items.pluck(:restaurant_id).uniq.first

    if existing_restaurant_id && existing_restaurant_id != item.restaurant_id
      raise "Cannot add items from different restaurants to the same order."
    end

    current_item = order_items.find_by(item_id: item.id)
    restaurant = item.restaurant

    if current_item 
      current_item.increment(:quantity)
    else
      current_item = order_items.build(item_id: item.id, restaurant_id: restaurant.id)
    end
    
    current_item   
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  belongs_to :user, optional: true
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 20 }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :user_id, presence: true
  validates :restaurant_id, presence: true

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  after_create_commit { broadcast_append_to self.room }

  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 20 }
  validates :address, presence: true, length: { maximum: 50 } 

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "id", "name", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :restaurant
  belongs_to :order, optional: true

  validates :restaurant_id, presence: true
  validates :item_id, presence: true
  validates :cart_id, presence: true
    

  def total_price
    item.price.to_i * quantity.to_i
  end

  def self.ransackable_attributes(auth_object = nil)
    ["cart_id", "created_at", "id", "item_id", "order_id", "quantity", "restaurant_id", "updated_at"]
  end

  
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :order_items
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 500 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to 'rooms' unless is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
        Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :restaurants
  has_many :orders
  has_many :items
  has_many :messages

  validates :name, presence: true
  validates_uniqueness_of :name

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }

  enum role: { basic_account: 0, bussiness_account: 1}
  validates :role, inclusion: { in: roles.keys }

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search].present?
      @restaurants = Restaurant.where('name LIKE ?', "%#{params[:search]}%").order('created_at desc').page(params[:page]).per(3)
    else
      @restaurants = Restaurant.order('created_at desc').page(params[:page]).per(3)
    end
  end

  def new
    @restaurant = Restaurant.new
  end
    
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id

    if @restaurant.save
      redirect_to restaurants_path(), notice: "Restaurant created successfully"
    else 
      render :new, status: :unprocessable_entity 
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant), notice: "Restaurant updated successfully"
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path(), notice: "Restaurant destroyed successfully"
  end

  private
   def set_restaurant
     @restaurant = Restaurant.find(params[:id])
   end

   def restaurant_params
     params.require(:restaurant).permit(:name, :description, :image)
   end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_count_over_one
    @cart.order_items.count > 0
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_author(item)
	user_signed_in? && current_user.id == item.user_id
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_count_over_one
    @order.order_items.count > 0
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def restaurant_author(restaurant)
	user_signed_in? && current_user.id == restaurant.user_id
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant do |form| %>
  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :restaurant_name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <% if user_signed_in? && current_user.role == "bussiness_account" &&  @restaurant.user_id == current_user.id %>
          <h2 class="title is-2">Update restaurant</h2>
          <%= render "form", restaurant: @restaurant %>
        <% else %>
          <p>You are not authorized to access this page.</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/restaurants/index.html.erb
<% if @restaurants.empty? %>
  <div class="alert alert-info">
    <h2>No results found.</h2>
  </div>
<% else %>
  <div class="d-flex input-group w-auto column">
    <%= form_tag( restaurants_path, method: "get") do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search restaurants", class: "form-control" %>
        <div class="input-group-btn">
          <%= button_tag "search", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
        </div>
      </div>
    <% end %>
   </div>
<% end %>

<div class= "column is-14">
  <% @restaurants.each do |restaurant| %>
    <%= link_to restaurant_path(restaurant) do %>
      <h5>Restaurant: <%= restaurant.name %></h5>
    <% end %>

    <h5>Description: <%= restaurant.description %></h5>

    <% if restaurant.image.present? %>
      <%= image_tag(restaurant.image, class: "image") %>
    <% end %>
    
    <hr />
  <% end %>
  <%= paginate @restaurants %>
</div>

app/views/restaurants/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <% if user_signed_in? && current_user.role == "bussiness_account" %>
          <h2 class="title is-2">Create a new restaurant</h2>
          <%= render "form", restaurant: @restaurant %>
        <% else %>
          <p>You are not authorized to access this page.</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/restaurants/show.html.erb
<div class= "column">
  <h2><%= @restaurant.name %></h2>
  <h4><%= @restaurant.description %></h4>
  <% if restaurant_author(@restaurant) %>
    <p>
      <%= link_to "Update",  edit_restaurant_path(@restaurant), class: "btn btn-info"%>
      <%= link_to "Delete", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are you sure" }, class: "btn btn-danger"%>
      <%= link_to "Add Food", new_restaurant_item_path(@restaurant),class: "btn btn-info"%>
    </p>
  <% end %>
  <hr />
  <h4>Items</h4>
  <%= render template: "items/show" %>
</div>