config/routes.rb
Rails.application.routes.draw do
  get 'news/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'restaurants#index'
  resources :restaurants do
    resources :items
  end
  
  get "users/:id", to: "users#show", as: "user"
  get '/restaurant_orders', to: 'orders#restaurant_orders', as: 'restaurant_orders'


  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  resources :order_items
  resources :carts
  resources :orders

  
  resources :rooms do
    resources :messages
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  def add_item(item)
    existing_restaurant_id = order_items.pluck(:restaurant_id).uniq.first

    if existing_restaurant_id && existing_restaurant_id != item.restaurant_id
      raise "Cannot add items from different restaurants to the same order."
    end

    current_item = order_items.find_by(item_id: item.id)
    restaurant = item.restaurant

    if current_item 
      current_item.increment(:quantity)
    else
      current_item = order_items.build(item_id: item.id, restaurant_id: restaurant.id)
    end
    
    current_item   
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  belongs_to :user, optional: true
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 20 }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :user_id, presence: true
  validates :restaurant_id, presence: true

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  after_create_commit { broadcast_append_to self.room }

  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 20 }
  validates :address, presence: true, length: { maximum: 50 } 

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "id", "name", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :restaurant
  belongs_to :order, optional: true

  validates :restaurant_id, presence: true
  validates :item_id, presence: true
  validates :cart_id, presence: true
    

  def total_price
    item.price.to_i * quantity.to_i
  end

  def self.ransackable_attributes(auth_object = nil)
    ["cart_id", "created_at", "id", "item_id", "order_id", "quantity", "restaurant_id", "updated_at"]
  end

  
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :order_items
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 500 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to 'rooms' unless is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
        Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :restaurants
  has_many :orders
  has_many :items
  has_many :messages

  validates :name, presence: true
  validates_uniqueness_of :name

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }

  enum role: { basic_account: 0, bussiness_account: 1}
  validates :role, inclusion: { in: roles.keys }

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_count_over_one
    @cart.order_items.count > 0
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_author(item)
	user_signed_in? && current_user.id == item.user_id
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_count_over_one
    @order.order_items.count > 0
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foody</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      <%= ".msg-#{current_user&.id}" %> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end
      }
    </style>
  </head>

  <body>
      <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>  
      <div class="topnav">
      <%= link_to "Foody", restaurants_path, class: "active" %>
        <% if user_signed_in? and current_user.role == "bussiness_account" %>
          <%= link_to "Add Restaurant", new_restaurant_path%>
          <%= link_to "Cart", cart_path(@cart) %>
          <%= link_to "Your Orders", orders_path %>
          <%= link_to "Restaurant Orders", restaurant_orders_path%>
          <%= link_to "Account", edit_user_registration_path%>
          <%= link_to "Chat", rooms_path%>
          <%= link_to "News", news_index_path%>
          <%= link_to "Sign-out", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% elsif user_signed_in? and current_user.role == "basic_account" %>
          <%= link_to "Cart", cart_path(@cart) %>
          <%= link_to "Your Orders", orders_path %>
          <%= link_to "Account", edit_user_registration_path%>
          <%= link_to "Chat", rooms_path%>
          <%= link_to "News", news_index_path%>
          <%= link_to "Sign-out", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "Sign-in", new_user_session_path %>
          <%= link_to "Sign-up", new_user_registration_path %>
        <% end %>
      </div>
     
    <%= yield %>
  </body>
</html>